# Tiltfile
docker_build('intelliquery', '../', live_update=[])

k8s_yaml('k8s/k8s.yaml')
k8s_yaml('k8s/postgres.yaml')

k8s_resource('postgres', resource_deps=[])
k8s_resource('intelliquery', port_forwards=8000, resource_deps=['postgres'])
