# Tiltfile
docker_build('my-llm-project', '../', live_update=[])

k8s_yaml('k8s/k8s.yaml')
k8s_yaml('k8s/postgres.yaml')

k8s_resource('postgres', resource_deps=[])
k8s_resource('my-llm-project', port_forwards=8000, resource_deps=['postgres'])
