apiVersion: v1
kind: ConfigMap
metadata:
  name: intelliquery-dev-env
data:
  DATABASE_URL: "postgresql+asyncpg://admin:securepass@postgres:5433/intelliquery"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelliquery
spec:
  selector:
    matchLabels:
      app: intelliquery
  template:
    metadata:
      labels:
        app: intelliquery
    spec:
      containers:
        - name: intelliquery
          image: intelliquery
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: intelliquery-dev-env
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: intelliquery
spec:
  type: NodePort
  selector:
    app: intelliquery
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
