apiVersion: v1
kind: ConfigMap
metadata:
  name: my-llm-dev-env
data:
  DATABASE_URL: "postgresql+asyncpg://admin:securepass@postgres:5433/myllmdb"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-llm-project
spec:
  selector:
    matchLabels:
      app: my-llm-project
  template:
    metadata:
      labels:
        app: my-llm-project
    spec:
      containers:
        - name: my-llm-project
          image: my-llm-project
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: my-llm-dev-env
          startupProbe:
            httpGet:
              path: /
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: my-llm-project
spec:
  type: NodePort
  selector:
    app: my-llm-project
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
